### ISSUE TITLE
Redundant line

### ISSUE THREAD

**Issue by edarin** [goclem/delineation#1]
I think that `density <- density[, .(density = sum(density)), by = pixel]` is already encompassed in function `match_image`.
https://github.com/goclem/delineation/blob/b02e6b9a2cb04f54759021cd35b4cea29ec5d08d/delineation_building.R#L163

**Comment by goclem** [comment]
Thanks a lot for the update! Indeed, I'll correct that. Luckily, that does not change the results since the second call has the same output as the first.
